#!/bin/bash
#SBATCH --gres=gpu:1       # Request GPU "generic resources"
#SBATCH --cpus-per-task=4  # Cores proportional to GPUs: 6 on Cedar, 16 on Graham.
#SBATCH --mem=32000M       # Memory proportional to GPUs: 32000 Cedar, 64000 Graham.
#SBATCH --time=0-1:00
#SBATCH --output=%N-%j.out

module load python/3.7 cuda cudnn
SOURCEDIR=~/scratch/FETS/Plain/

source ~/anaconda3/etc/profile.d/conda.sh

source $SOURCEDIR/new_env/bin/activate


mkdir $SLURM_TMPDIR/Data
tar xf ~/scratch/FETS/Data/FETS.tar -C $SLURM_TMPDIR/Data

python $SOURCEDIR/main.py $SLURM_TMPDIR/Data/